name: Build and Release

on:
  push:
    tags: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            architecture: amd64
          - runner: ubuntu-latest
            architecture: arm64
    
    steps:
    - name: Update system and install dependencies
      run: |
        sudo apt update -y
        sudo apt install -y git build-essential git wget curl
        
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Make build script executable
      run: chmod +x ./build_all_profiles.sh
        
    - name: Run build script
      run: |
        git config --global --add safe.directory /__w/tinylinux-scripts/tinylinux-scripts
        git submodule init
        git submodule update
        sudo ./build_all_profiles.sh

    - name: Create final zip package
      run: |
        VERSION_DIR=$(date '+%y.%m.%d')
        sudo zip -r tinylinux-scripts-latest.zip "$VERSION_DIR" build_mods_driver.tar.bz2

    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: tinylinux-scripts-latest.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}