name: Build and Release

on:
  push:
    tags: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            architecture: amd64
          - runner: ubuntu-latest
            architecture: arm64
    
    steps:
    - name: Update system and install dependencies
      run: |
        sudo apt update -y
        sudo apt install -y git build-essential git wget curl
        
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Make build script executable
      run: chmod +x ./build_all_profiles.sh
        
    - name: Run build script
      run: |
        git config --global --add safe.directory /__w/tinylinux-scripts/tinylinux-scripts
        git submodule init
        git submodule update
        sudo ./build_all_profiles.sh
      
    - name: Create tar archive
      run: |
        # 使用当前 tag 名称作为文件名
        TAG_NAME=${GITHUB_REF#refs/tags/}
        FINAL_FILENAME="build-output-$TAG_NAME-${{ matrix.arch }}.tar.gz"
        sudo tar -czf "$FINAL_FILENAME" .
        
    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: build-*.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}